### ISSUE TITLE
建议功能：自动忘记密码

### ISSUE THREAD

**Issue by Sukwants** [Night-stars-1/LiteLoaderQQNT-Plugin-QQPromote#39]
自动忘记密码过后下次登录需要重新输入密码而无需手机验证，可以做到和旧版 QQ 一样的登陆体验。

**Comment by Night-stars-1** [comment]
这个恐怕做不到，目前修改只能在js层面

**Comment by Sukwants** [comment]
设置面板 - 登录设置那里有一个清空密码的按钮，能不能通过类似这个按钮的方式实现 /kel

**Comment by Night-stars-1** [comment]
好的，之后看一下

**Comment by Night-stars-1** [comment]
已经添加，llapi需要更新到最新版
2985235d496a33178fafb8877e3e10977b1c8a17

**Comment by Night-stars-1** [comment]
这个是临时的后面可能会修改成旧版，在登录界面勾选的样式
