### ISSUE TITLE
链接预览请考虑增加缓存

### ISSUE THREAD

**Issue by pigeon2049** [Night-stars-1/LiteLoaderQQNT-Plugin-QQPromote#41]
同一条消息每次打开都会发出请求 很多网站有频次限制会显示验证码
![image](https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-RepeatMsg/assets/17434465/b13ad1e5-f59f-4467-af0f-120c60b540b9)
是否考虑解析过一次的消息id直接显示上次缓存的预览结果?

**Comment by Night-stars-1** [comment]
好的，后台会加上的

**Comment by Night-stars-1** [comment]
f0408b627cf44890f5549ced4a97482fb9c86130
已增加
