### ISSUE TITLE
QQ9.9.7，装了插件就会报错

### ISSUE THREAD

**Issue by FinaFina233** [Night-stars-1/LiteLoaderQQNT-Plugin-QQPromote#45]
![1705998009788](https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-QQPromote/assets/52440333/445218a1-fdf7-4c10-aaec-d70b8f8fdb74)

**Comment by heerxingen** [comment]
emm这种不应该去liteloaderQQNT的repo反馈吗

**Comment by LanYunDev** [comment]
<img width="790" alt="image" src="https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-QQPromote/assets/95263282/5f2eef41-22d0-426f-87ee-63fc2bc6cdb5">
你应该手动创建这个目录的文件夹.

**Comment by FinaFina233** [comment]
> emm这种不应该去liteloaderQQNT的repo反馈吗

Liteloader没问题，装了这个插件就报了

**Comment by FinaFina233** [comment]
> <img alt="image" width="790" src="https://private-user-images.githubusercontent.com/95263282/298914563-5f2eef41-22d0-426f-87ee-63fc2bc6cdb5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMDkyODcsIm5iZiI6MTcwNjAwODk4NywicGF0aCI6Ii85NTI2MzI4Mi8yOTg5MTQ1NjMtNWYyZWVmNDEtMjJkMC00MjZmLTg3ZWUtNjNmYzJiYzZjZGI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDExMjMwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxNmZkMTViZWUwMWI5ZTllNDU0MmY5ZjA0NjcyM2Q4Y2QwODE5OWY0ZTM2YTEzOTAzODIwZmJhYmIxYTU3OTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1DpSKFYHQUF41tPWq-hHX83gMLCGrhkLEVIKc-rppsk"> 你应该手动创建这个目录的文件夹.

谢谢，可以了
