### ISSUE TITLE
复读机复读消息时 艾特信息丢失 只有文本

### ISSUE THREAD

**Issue by Huanting93** [Night-stars-1/LiteLoaderQQNT-Plugin-QQPromote#46]

**Comment by Night-stars-1** [comment]
不太理解
![image](https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-QQPromote/assets/99261160/70fbec21-27f2-496b-af36-0382b51691fe)

**Comment by Huanting93** [comment]
> 不太理解 ![image](https://private-user-images.githubusercontent.com/99261160/298890638-70fbec21-27f2-496b-af36-0382b51691fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNjAxNDEsIm5iZiI6MTcwNjA1OTg0MSwicGF0aCI6Ii85OTI2MTE2MC8yOTg4OTA2MzgtNzBmYmVjMjEtMjdmMi00OTZiLWFmMzYtMDM4MmI1MTY5MWZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDAxMzA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwODQ0MjljOTQ1MzMwNGRlNGU2NTBjYjU5OWE1MzcxYTZiZDQyYzJhNmQwZWNkZWQzZWZiNDQzMjcxNGJiMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HjPH2kCQzRtpLvleMR5mmUpwRVFZTnBHrPwNaaEXYgg)

![e3a6141417e45a9d87e793c15f4e1c05](https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-QQPromote/assets/36955112/0f571160-75a0-4c56-b038-ab1ab79e79d8)
高亮是没了的  就是说复读的只是文本

**Comment by Huanting93** [comment]
> > > 不太理解 ![image](https://private-user-images.githubusercontent.com/99261160/298890638-70fbec21-27f2-496b-af36-0382b51691fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNjAxNDEsIm5iZiI6MTcwNjA1OTg0MSwicGF0aCI6Ii85OTI2MTE2MC8yOTg4OTA2MzgtNzBmYmVjMjEtMjdmMi00OTZiLWFmMzYtMDM4MmI1MTY5MWZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDAxMzA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwODQ0MjljOTQ1MzMwNGRlNGU2NTBjYjU5OWE1MzcxYTZiZDQyYzJhNmQwZWNkZWQzZWZiNDQzMjcxNGJiMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HjPH2kCQzRtpLvleMR5mmUpwRVFZTnBHrPwNaaEXYgg)
> > 
> > 
> > ![e3a6141417e45a9d87e793c15f4e1c05](https://private-user-images.githubusercontent.com/36955112/299149346-0f571160-75a0-4c56-b038-ab1ab79e79d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNzcxMDAsIm5iZiI6MTcwNjA3NjgwMCwicGF0aCI6Ii8zNjk1NTExMi8yOTkxNDkzNDYtMGY1NzExNjAtNzVhMC00YzU2LWIwMzgtYWIxYWI3OWU3OWQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDA2MTMyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5YTFjNzcxYWU3MmI4NDFlOTEwMWY3MDBlNGE0YWYwZmMyYzNmZWIzMDlkMGMzOWM4ODE1MTNkNjc5ZmU3NGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H15XE_r1rHaNWabYRwSvrUbC5r06uFos-PejX4IdX4A) 高亮是没了的 就是说复读的只是文本
> 
> 这是正常现象

好像现在是调转发接口实现的复读，有没有别的实现方法可以实现不丢失艾特信息呢
