### ISSUE TITLE
群聊好友名称补全<>中显示的并非是备注而是qq昵称

### ISSUE THREAD

**Issue by BalconyJH** [Night-stars-1/LiteLoaderQQNT-Plugin-QQPromote#47]
> - 插件版本 1.2.5
> 
> - LLAPI版本 1.1.9
> 
> - Liteloader版本 1.0.0

### 描述问题

群聊好友名称补全<>中显示的并非是备注而是qq昵称

![image](https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-QQPromote/assets/73932916/b944b0de-d1e9-4ad7-8032-3792d5db13f5)

![image](https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-QQPromote/assets/73932916/af26e195-4323-439c-b3da-30a6501d5ce3)

### 期望的结果

<>中显示备注
![image](https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-QQPromote/assets/73932916/16f29fcd-7a8a-44d9-8554-083f763ae688)

**Comment by Night-stars-1** [comment]
感谢反馈，调整为了如果备注不存在则显示qq名称
