### ISSUE TITLE
左上角有圆圈遮罩

### ISSUE THREAD

**Issue by LanYunDev** [Night-stars-1/LiteLoaderQQNT-Plugin-QQPromote#48]
版本信息: macOS: 13.5 QQ: v6.9.25.20979 LiteLoaderQQNT-Plugin-QQPromote :v1.3.1
在登录界面,左上角有圆圈遮罩,如图所示.
<img width="109" alt="image" src="https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-QQPromote/assets/95263282/2e60212e-afb5-455c-835b-d7ea2a735018">
<img width="353" alt="image" src="https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-QQPromote/assets/95263282/64ea16fb-aa1a-4339-9a6b-c7ffb1ee50d7">

能否隐藏?

**Comment by Night-stars-1** [comment]
这个是忘记密码选项，不是很影响应该，这个界面停留时间不长

**Comment by LanYunDev** [comment]
哦哦,原来如此,那确实没啥大问题.
