### ISSUE TITLE
当网页为gb2312编码时,网页预览会乱码

### ISSUE THREAD

**Issue by xmexg** [Night-stars-1/LiteLoaderQQNT-Plugin-QQPromote#57]
像这样  
https://www.qlit.edu.cn/  
![image](https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-QQPromote/assets/42137636/d3776999-2950-45f7-aab1-03532ef47ae0)

**Comment by Night-stars-1** [comment]
不好解决，用buffer来转换编码要花费时间长，这样做代价大了，因为这样会影响其他utf-8的响应时间

**Comment by xmexg** [comment]
先按utf8读,英文貌似不会乱码(连接正常显示),然后读<head></head>里的<meta>,检查有没有指定charset,如果有的话不是utf8就按指定的编码再读一遍,没有不管.这样?

**Comment by Night-stars-1** [comment]
> 先按`utf8`读,英文貌似不会乱码(连接正常显示),然后读`<head></head>`里的`<meta>`,检查有没有指定`charset`,如果有的话不是`utf8`就按指定的编码再读一遍,没有不管.这样?
> 
> 或者给包含连接的右键菜单加个更换编码的按钮,由用户选择编码

这样也行，但是要等一段时间，这几天可能要弄一下其他项目

**Comment by xmexg** [comment]
好有趣,变成`utf-8`编码的烟花了
![Screenshot_2024-02-10_14_02_12](https://github.com/Night-stars-1/LiteLoaderQQNT-Plugin-QQPromote/assets/42137636/41728934-9007-43db-805c-0d3e27dc4856)

**Comment by xmexg** [comment]
# 快速寻找`gb2312`编码的网站  
## 通过NerdyData搜素引擎  
https://www.nerdydata.com/reports/new?search={%22all%22:[{%22type%22:%22code%22,%22value%22:%22charset=%27gb2312%27%22,%22name%22:%22charset=%27gb2312%27%22}],%22any%22:[],%22none%22:[]}  
## 已知的`gb2312`网站
+ https://www.hexun.com/
+ https://thethirdmedia.com/
+ https://www.iresearch.cn/
+ http://swu.edu.cn/
